name: shopywell
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.9
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  get: ^4.7.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/
